C     DEBUG VERSION: Added print statements to trace opacity computation
C     Original file: spectrv.for
C     Location: Lines 231-238 (opacity computation from coefficients)
C     
 2005 C1=(WAVE-HALFEDGE(IEDGE))*(WAVE-WLEDGE(IEDGE+1))/DELEDGE(IEDGE)
      C2=(WLEDGE(IEDGE)-WAVE)*(WAVE-WLEDGE(IEDGE+1))*2./DELEDGE(IEDGE)
      C3=(WAVE-WLEDGE(IEDGE))*(WAVE-HALFEDGE(IEDGE))/DELEDGE(IEDGE)
C     DEBUG: Print interpolation coefficients
      IF(IEDGE.EQ.183.OR.IEDGE.EQ.1)THEN
      WRITE(6,9996)NU,WAVE,IEDGE,C1,C2,C3,C1+C2+C3
 9996 FORMAT(' DEBUG SPECTRV: NU=',I4,' WAVE=',F10.3,' IEDGE=',I3,
     1 ' C1=',1PE15.8,' C2=',1PE15.8,' C3=',1PE15.8,' SUM=',1PE15.8)
      ENDIF
      DO 2006 J=1,NRHOX
C     DEBUG: Print coefficients and computed opacity for first few layers
      IF((J.LE.5.OR.J.EQ.NRHOX).AND.(IEDGE.EQ.183.OR.IEDGE.EQ.1))THEN
      LOGACONT=C1*CONTABS(1,IEDGE,J)+C2*CONTABS(2,IEDGE,J)+
     1 C3*CONTABS(3,IEDGE,J)
      ACONT_COMP=10.**LOGACONT
      WRITE(6,9995)J,IEDGE,CONTABS(1,IEDGE,J),CONTABS(2,IEDGE,J),
     1 CONTABS(3,IEDGE,J),LOGACONT,ACONT_COMP
 9995 FORMAT(' DEBUG SPECTRV: J=',I3,' IEDGE=',I3,' CONTABS(1)=',
     1 1PE15.8,' CONTABS(2)=',1PE15.8,' CONTABS(3)=',1PE15.8,
     2 ' LOGACONT=',1PE15.8,' ACONT=',1PE15.8)
      ENDIF
      ACONT(J)=10.**(C1*CONTABS(1,IEDGE,J)+C2*CONTABS(2,IEDGE,J)+
     1 C3*CONTABS(3,IEDGE,J))
 2006 SIGMAC(J)=10.**(C1*CONTSCAT(1,IEDGE,J)+C2*CONTSCAT(2,IEDGE,J)+
     1 C3*CONTSCAT(3,IEDGE,J))

